/**
 * Storytime Agent Types
 * Core interfaces for the parent digital twin storytelling system
 */

/** Parent persona derived from onboarding */
export interface ParentPersona {
  name: string;
  storytellingStyle: string; // e.g., "warm and playful", "educational", "adventurous"
  voiceTone: string; // e.g., "gentle", "enthusiastic", "calm"
  favoriteThemes: string[]; // e.g., ["nature", "friendship", "courage"]
  culturalBackground?: string;
  specialPhrases?: string[]; // phrases the parent likes to use
  values: string[]; // e.g., ["kindness", "curiosity", "perseverance"]
  avoidTopics?: string[]; // topics to avoid
}

/** Child description from onboarding */
export interface ChildProfile {
  name: string;
  age: number;
  interests: string[]; // e.g., ["dinosaurs", "space", "princesses"]
  fears?: string[]; // to avoid in stories
  favoriteCharacters?: string[];
  attentionSpan: "short" | "medium" | "long";
  preferredStoryLength: "quick" | "medium" | "bedtime";
}

/** Combined context from onboarding */
export interface StoryContext {
  parentPersona: ParentPersona;
  childProfile: ChildProfile;
  rawMarkdown: string; // The full markdown generated by onboarding agent
}

/** Story synopsis generated by synopsis agent */
export interface StorySynopsis {
  title: string;
  premise: string;
  mainCharacters: Array<{
    name: string;
    description: string;
    role: "protagonist" | "sidekick" | "mentor" | "antagonist" | "supporting";
  }>;
  setting: string;
  theme: string;
  moralLesson?: string;
  estimatedPages: number;
  outline: string[]; // Brief outline of major story beats
}

/** A single page/chunk of the story */
export interface StoryPage {
  pageNumber: number;
  content: string;
  suggestedPause?: boolean; // Suggest a pause for interaction
  interactionPrompt?: string; // e.g., "Can you roar like a dinosaur?"
}

/** Full story state for the storytelling agent */
export interface StoryState {
  synopsis: StorySynopsis;
  context: StoryContext;
  pages: StoryPage[];
  currentPage: number;
  isComplete: boolean;
}

/** Input for onboarding agent */
export interface OnboardingInput {
  transcript: string; // Raw transcript from parent onboarding conversation
}

/** Input for synopsis agent */
export interface SynopsisInput {
  context: StoryContext;
  childRequest: string; // What the child asked for, could be vague
}

/** Input for storytelling agent */
export interface StorytellingInput {
  synopsis: StorySynopsis;
  context: StoryContext;
  previousPages: StoryPage[];
}

/** Output from storytelling agent for each page */
export interface StorytellingOutput {
  page: StoryPage;
  isLastPage: boolean;
}
